[package]
name = "compatibility-suite"
version = "0.0.0"
edition = "2021"

[dev-dependencies]
anyhow = "1.0.71"
async-trait = "0.1.68"
bytes = "1.4.0"
cucumber = "0.19"
futures = "0.3"
itertools = "0.10.5"
maplit = "1.0.2"
pact_models = "~1.1.7"
pact_matching = { version = "1.1.0", path = "../rust/pact_matching" }
pact_mock_server = { version = "1.1.0", path = "../rust/pact_mock_server" }
pact_verifier = { version = "1.0.0", path = "../rust/pact_verifier" }
reqwest = { version = "0.11.17", features = ["rustls-tls-native-roots", "json"] }
serde_json = "1.0.96"
sxd-document = "0.3.2"
tokio = { version = "1.28.1", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter", "tracing-log", "fmt"] }
uuid = { version = "1.3.3", features = ["v4"] }

[[test]]
name = "v1_consumer"
harness = false

[[test]]
name = "v1_provider"
harness = false

[[test]]
name = "v2_consumer"
harness = false

[[test]]
name = "v2_provider"
harness = false
