[package]
name = "pact_verifier_cli"
version = "0.7.0"
authors = ["Ronald Holshausen <uglyog@gmail.com>"]
edition = "2018"
description = "Standalone pact verifier for provider pact verification"
homepage = "http://www.pact.io"
repository = "https://github.com/pact-foundation/pact-reference/blob/master/rust/pact_verifier_cli"
readme = "README.md"
keywords = ["testing", "pact", "cdc"]
license = "MIT"
exclude = [
    "*.iml"
]

[dependencies]
libc = "0.2.9"
clap = "2.33.0"
pact_matching = { version = "0.5.8", path = "../pact_matching" }
pact_verifier = { version = "0.8.0", path = "../pact_verifier" }
simplelog = "0.7"
log = "0.4.8"
maplit = "0.1.3"
lazy_static = "0.1.15"
rand = "0.3"
regex = "0.1"
tokio = { version = "0.2.9", features = ["rt-core", "macros"] }

[dev-dependencies]
quickcheck = "0.2"
expectest = "0.5.1"
