[package]
name = "pact_verifier_cli"
version = "0.8.5"
authors = ["Ronald Holshausen <uglyog@gmail.com>"]
edition = "2018"
description = "Standalone pact verifier for provider pact verification"
homepage = "http://www.pact.io"
repository = "https://github.com/pact-foundation/pact-reference/blob/master/rust/pact_verifier_cli"
readme = "README.md"
keywords = ["testing", "pact", "cdc"]
license = "MIT"
exclude = [
    "*.iml"
]

[dependencies]
pact_verifier_ffi = { version = "0.0.0", path = "../pact_verifier_ffi" }
tokio = { version = "1", features = ["full"] }
