[package]
name = "pact_mock_server"
version = "1.0.1"
authors = ["Ronald Holshausen <ronald.holshausen@gmail.com>"]
edition = "2021"
description = "Pact-Rust support library that implements in process mock server"
homepage = "https://www.pact.io"
repository = "https://github.com/pact-foundation/pact-reference/blob/master/rust/pact_mock_server"
readme = "README.md"
keywords = ["testing", "pact", "cdc", "mockserver"]
license = "MIT"
exclude = [
    "*.iml"
]

[dependencies]
anyhow = "1.0.66"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "1.0.87"
pact_matching = { version =  "1.0.5", path = "../pact_matching" }
pact_models = "1.0.4"
maplit = "1.0.2"
lazy_static = "1.4.0"
uuid = { version = "1.2.1", features = ["v4"] }
itertools = "0.10.5"
tokio = { version = "1.23.0", features = ["full"] }
futures = "0.3.25"
hyper = { version = "0.14.22", features = ["full"] }
bytes = "1.2.1"
hyper-rustls = "0.23.0"
rustls = "0.20.7"
tokio-rustls = "0.23.4"
rustls-pemfile = "1.0.1"
thiserror = "1.0.37"
pact-plugin-driver = "0.3.2"
tracing = "0.1.37" # This needs to be the same version across all the libs (i.e. plugin driver)
tracing-core = "0.1.30"  # This needs to be the same version across all the pact libs (i.e. pact ffi)
url = "2.3.1"

[dev-dependencies]
quickcheck = "1.0.3"
expectest = "0.12.0"
reqwest = { version = "0.11.12", default-features = false, features = ["rustls-tls-native-roots", "blocking", "json"] }
env_logger = "0.10.0"
test-env-log = "0.2.8"
