[package]
name = "pact_mock_server_cli"
version = "0.7.4"
authors = ["Ronald Holshausen <uglyog@gmail.com>"]
edition = "2018"
description = "Standalone pact mock server for consumer pact tests"
homepage = "http://www.pact.io"
repository = "https://github.com/pact-foundation/pact-reference/blob/master/rust/pact_mock_server_cli"
readme = "README.md"
keywords = ["testing", "pact", "cdc", "mockserver"]
license = "MIT"
exclude = [
    "*.iml"
]

[dependencies]
libc = "0.2.9"
clap = "2.31.2"
serde_json = "1.0"
pact_models = { version =  "0.0", path = "../pact_models" }
pact_matching = { version = "0.9", path = "../pact_matching" }
pact_mock_server = { version = "0.7.12", path = "../pact_mock_server" }
simplelog = "0.9"
log = "0.4"
uuid = { version = "0.8", features = ["v4"] }
maplit = "1.0.2"
rand = "0.8"
webmachine-rust = "0.2.2"
regex = "1"
lazy_static = "1.4.0"
reqwest = { version = "0.11", features = ["json"] }
url = "2.1.1"
http = "0.2"
futures = "0.3.0"
tokio = { version = "1", features = ["full"] }
hyper = "0.14.0"
itertools = "0.10.0"
anyhow = "1.0.40"

[dev-dependencies]
quickcheck = "1"
expectest = "0.12.0"
