[package]
name = "pact_mock_server_cli"
version = "1.0.1"
authors = ["Ronald Holshausen <ronald.holshausen@gmail.com>"]
edition = "2021"
description = "Standalone pact mock server for consumer pact tests"
homepage = "https://www.pact.io"
repository = "https://github.com/pact-foundation/pact-reference/blob/master/rust/pact_mock_server_cli"
readme = "README.md"
keywords = ["testing", "pact", "cdc", "mockserver"]
license = "MIT"
exclude = [
    "*.iml"
]

[dependencies]
clap = { version = "3.2.23", features = ["cargo"] }
serde_json = "1.0.95"
pact_models = "~1.1.4"
pact_matching = { version = "~1.1.1", path = "../pact_matching" }
pact_mock_server = { version = "~1.1.0", path = "../pact_mock_server" }
simplelog = "0.12.1"
log = "0.4.17"
uuid = { version = "1.3.0", features = ["v4"] }
maplit = "1.0.2"
rand = "0.8.5"
webmachine-rust = "0.2.2"
regex = "1.7.3"
lazy_static = "1.4.0"
reqwest = { version = "0.11.16", default-features = false, features = ["rustls-tls-native-roots", "blocking", "json"] }
url = "2.3.1"
http = "0.2.9"
futures = "0.3.28"
tokio = { version = "1", features = ["full"] }
hyper = "0.14.25"
itertools = "0.10.5"
anyhow = "1.0.70"

[dev-dependencies]
quickcheck = "1"
expectest = "0.12.0"
trycmd = "0.14.13"
test-log = "0.2.11"
env_logger = "0.10.0"
