[package]
name = "pact_verifier"
version = "0.13.20"
authors = ["Ronald Holshausen <ronald.holshausen@gmail.com>"]
edition = "2021"
description = "Pact-Rust support library that implements provider verification functions"
documentation = "https://docs.rs/pact_verifier/"
homepage = "https://www.pact.io"
repository = "https://github.com/pact-foundation/pact-reference/blob/master/rust/pact_verifier"
readme = "README.md"
keywords = ["testing", "pact", "cdc"]
license = "MIT"
exclude = [
    "*.iml"
]

[dependencies]
anyhow = "1.0.66"
serde = "1.0.147"
serde_json = "1.0.87"
pact_matching = { version = "1.0.2", path = "../pact_matching" }
pact_models = "1.0.2"
pact-plugin-driver = "0.2.2"
maplit = "1.0.2"
lazy_static = "1.4.0"
itertools = "0.10.5"
ansi_term = "0.12.1"
regex = "1.7.0"
difference = "2.0.0"
futures = "0.3.25"
mime = "0.3.16"
bytes = "1.2.1"
tokio = { version = "1.23.0", features = ["full"] }
http = "0.2.8"
async-trait = "0.1.58"
thiserror = "1.0.37"
base64 = "0.20.0"
urlencoding = "2.1.2"
tracing = "0.1.37" # This needs to be the same version across all the libs (i.e. plugin driver and pact ffi)
tracing-core = "0.1.30"  # This needs to be the same version across all the pact libs (i.e. plugin driver and pact ffi)
url = "2.3.1"

[dependencies.reqwest]
version = "0.11.12"
default-features = false
features = ["rustls-tls-native-roots", "blocking", "json"]

[dependencies.serde_with]
version = "2.0.1"
features = ["json"]

[lib]
crate-type = ["cdylib", "rlib"]

[dev-dependencies]
quickcheck = "1.0.3"
expectest = "0.12.0"
env_logger = "0.10.0"
pact_consumer = { version = "0.10.0", path = "../pact_consumer" }
test-log = { version = "0.2.11", features = ["trace"] }
tracing-subscriber = { version = "0.3.16", features = ["env-filter", "tracing-log", "fmt"] }
