[package]
name = "pact_consumer"
version = "0.7.6"
authors = ["Ronald Holshausen <uglyog@gmail.com>", "Eric Kidd <git@randomhacks.net>"]
edition = "2018"
description = "Pact-Rust module that provides support for writing consumer pact tests"
documentation = "https://docs.rs/pact_consumer/0.5.4/pact_consumer/"
homepage = "http://www.pact.io"
repository = "https://github.com/pact-foundation/pact-reference/blob/master/rust/pact_consumer"
readme = "README.md"
keywords = ["testing", "pact", "cdc"]
license = "MIT AND Apache-2.0"
exclude = [
    "*.iml"
]

[dependencies]
libc = "0.2.9"
pact_models = { version =  "0.0", path = "../pact_models" }
pact_matching = { version = "0.9", path = "../pact_matching" }
pact_mock_server = { version = "0.7.12", path = "../pact_mock_server" }
log = "0.4.0"
maplit = "1.0.2"
lazy_static = "1.4.0"
regex = "1"
serde_json = "1.0"
itertools = "0.10.0"
url = "2.1"
uuid = { version = "0.8", features = ["v4"] }
futures = "0.3"
tokio = { version = "1", features = ["full"] }
anyhow = "1.0.40"

[dev-dependencies]
quickcheck = "1"
env_logger = "0.8"
expectest = "0.12.0"
reqwest = { version = "0.11", features = ["default-tls"] }
serde = { version = "^1.0", features = ["derive"] }
