[package]
name = "pact_models"
version = "0.0.2"
authors = ["Ronald Holshausen <rholshausen@dius.com.au>"]
edition = "2018"
description = "Pact-Rust support library that provides the core models for dealing with Pact files"
documentation = "https://docs.rs/pact_models/0.0.2/pact_models/"
homepage = "http://www.pact.io"
repository = "https://github.com/pact-foundation/pact-reference/blob/master/rust/pact_models"
readme = "README.md"
keywords = ["testing", "pact", "cdc"]
license = "MIT"
exclude = [
    "*.iml"
]

[dependencies]
anyhow = "1.0.40"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
log = "0.4.8"
maplit = "1.0.2"
itertools = "0.10.0"
bytes = { version = "1", features = ["serde"] }
lazy_static = "1.4.0"
mime = "0.3.16"
base64 = "0.13.0"
regex = "1"

[dev-dependencies]
expectest = "0.12.0"
