[package]
name = "pact_models"
version = "0.4.7"
authors = ["Ronald Holshausen <rholshausen@dius.com.au>"]
edition = "2021"
description = "Pact-Rust support library that provides the core models for dealing with Pact files"
homepage = "http://www.pact.io"
repository = "https://github.com/pact-foundation/pact-reference/blob/master/rust/pact_models"
readme = "README.md"
keywords = ["testing", "pact", "cdc"]
license = "MIT"
exclude = [
    "*.iml"
]
build = "build.rs"

[dependencies]
anyhow = "1.0.57"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
maplit = "1.0.2"
itertools = "0.10.3"
bytes = { version = "1", features = ["serde"] }
lazy_static = "1.4.0"
mime = "0.3.16"
base64 = "0.13.0"
regex = "1.5.5"
nom = "7.1.1"
chrono = { version = "0.4.19", features = ["std", "clock"], default-features = false }
chrono-tz = "0.6.1"
lenient_semver = "0.4.2"
sxd-document = "0.3.2"
indextree = "4.4.0"
rand = "0.8.5"
hex = "0.4.3"
rand_regex = "0.15.1"
regex-syntax = "0.6.25"
logos = "0.12.0"
logos-iter = "0.1.2"
ariadne = "0.1.5"
semver = "1.0.9"
tracing = "=0.1.36" # This needs to be the same version across all the libs (i.e. plugin driver)

[target.'cfg(not(target_family = "wasm"))'.dependencies]
fs2 = "0.4.3"
onig = { version = "6.4.0", default-features = false }
reqwest = { version = "0.11.10", default-features = false, features = ["rustls-tls-native-roots", "blocking", "json"] }
uuid = { version = "1.1.2", features = ["v4"] }

[target.'cfg(target_family = "wasm")'.dependencies]
uuid = { version = "1.1.2", features = ["v4"] }

[dev-dependencies]
expectest = "0.12.0"
env_logger = "0.9.0"
speculate = "0.1.2"
rstest = "0.15.0"
hamcrest2 = "0.3.0"
test-log = "0.2.10"
pretty_assertions = "1.2.1"
trim-margin = "0.1.0"

[build-dependencies]
parse-zoneinfo = "0.3.0"
maplit = "1.0.2"
