name: Pact-Rust FFI Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ ubuntu-latest, windows-latest, macos-latest ]
        rust: [ stable ]
    env:
      pact_do_not_track: true
    steps:
      - uses: actions/checkout@v3
      - run: rustc --version || true
        shell: bash
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - name: Install shared mime info DB
        if: runner.os == 'macOS'
        run: brew install shared-mime-info
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt
      - name: Install doxygen
        if: runner.os == 'Linux'
        run: sudo apt-get install -y doxygen
      - name: Build pact_ffi with CMake
        run: ./ci-build.sh
        working-directory: rust/pact_ffi
        shell: bash
      - name: Run the C FFI tests
        if: runner.os == 'Linux'
        working-directory: c/consumer-verification
        run: |
          sudo apt update
          sudo apt install libcurl4-openssl-dev
          /usr/bin/aclocal
          autoconf
          automake --add-missing
          ./configure
          make
          src/consumer-verification basic ../../rust/target/debug/libpact_ffi.so
          src/consumer-verification error ../../rust/target/debug/libpact_ffi.so
